version: '2'
services:
  wordpress:
     image: wordpress:latest
     container_name: wordpress
     volumes:
       - ./src:/var/www/html/
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: database-2.coft0uf6izio.us-east-1.rds.amazonaws.com:3306
       WORDPRESS_DB_USER: admin
       WORDPRESS_DB_PASSWORD: Nini8079
       WORDPRESS_DB_NAME: wordpress